def domain_specific_replacements() -> dict[str, str]:
    replacement_mapping = {
        'unet': 'U-Net',
        'u-net': 'U-Net',
        'UNET': 'U-Net',
        'uNET': 'U-Net',
        'U-net': 'U-Net',
        'U-NET': 'U-Net',

        'inceptionResNet v2': 'InceptionResNetV2',
        'inceptionResNetv2': 'InceptionResNetV2',
        'inceptionResNetV2': 'InceptionResNetV2',
        'inceptionResNet-V2': 'InceptionResNetV2',
        'inceptionResNet-v2': 'InceptionResNetV2',
        'inceptionResNet-V2': 'InceptionResNetV2',
        'InceptionResNet v2': 'InceptionResNetV2',
        'InceptionResNetv2': 'InceptionResNetV2',
        'InceptionResNet-V2': 'InceptionResNetV2',
        'InceptionResNet-v2': 'InceptionResNetV2',
        'InceptionResNet-V2': 'InceptionResNetV2',
        'Inception-ResNet-v2': 'InceptionResNetV2',
        'Inception-ResNet-v2': 'InceptionResNetV2',
        'Inception-ResNet-V2': 'InceptionResNetV2',
        'inception-resnet-v2': 'InceptionResNetV2',

        'resnext50': 'ResNeXt50',
        'resnext-50': 'ResNeXt50',
        'resnext 50': 'ResNeXt50',
        'ResNext-50': 'ResNeXt50',

        'resnext101': 'ResNeXt101',
        'resnext-101': 'ResNeXt101',
        'resnext 101': 'ResNeXt101',
        'ResNext-101': 'ResNeXt101',

        'ResNext': 'ResNeXt',

        'ResNet18': 'ResNet-18',
        'ResNet-18': 'ResNet-18',
        'ResNet 18': 'ResNet-18',
        'Res-Net-18': 'ResNet-18',
        'Res-Net 18': 'ResNet-18',
        'Res-Net18': 'ResNet-18',

        'ResNet50': 'ResNet-50',
        'ResNet-50': 'ResNet-50',
        'ResNet 50': 'ResNet-50',
        'Res-Net-50': 'ResNet-50',
        'Res-Net 50': 'ResNet-50',
        'Res-Net50': 'ResNet-50',

        'ResNet101': 'ResNet-101',
        'ResNet-101': 'ResNet-101',
        'ResNet 101': 'ResNet-101',
        'Res-Net-101': 'ResNet-101',
        'Res-Net 101': 'ResNet-101',
        'Res-Net101': 'ResNet-101',

        'ResNetv2': 'ResNetV2',
        'ResNet-v2': 'ResNetV2',
        'ResNet v2': 'ResNetV2',
        'Res-Net-v2': 'ResNetV2',
        'Res-Net v2': 'ResNetV2',
        'Res-Netv2': 'ResNetV2',
        'ResNet-V2': 'ResNetV2',
        'ResNet V2': 'ResNetV2',
        'Res-Net-V2': 'ResNetV2',
        'Res-Net V2': 'ResNetV2',
        'Res-NetV2': 'ResNetV2',

        'Res-Net': 'ResNet',

        'inception v3': 'InceptionV3',
        'Inception V3': 'InceptionV3',
        'Inception v3': 'InceptionV3',
        'Inception-V3': 'InceptionV3',
        'Inception-v3': 'InceptionV3',

        'inception v4': 'InceptionV4',
        'Inception V4': 'InceptionV4',
        'Inception v4': 'InceptionV4',
        'Inception-V4': 'InceptionV4',
        'Inception-v4': 'InceptionV4',

        'VGG-16': 'VGG16',
        'VGG-19': 'VGG19',

        'tele-medicine': 'telemedicine',
        'Tele-Medicine': 'Telemedicine',
        'Tele-medicine': 'Telemedicine',

        'tele-ophthalmology': 'teleophthalmology',
        'Tele-Ophthalmology': 'Teleophthalmology',
        'Tele-ophthalmology': 'Teleophthalmology',
    }
    return replacement_mapping


def exact_replacements() -> dict[str, str]:
    replacements: dict[str, str] = {
        "aao": "american academy of ophthalmology",
        'acd': 'anterior chamber depth',
        "ad": "alzheimer's disease",
        "adls": "automated deep learning diabetic retinopathy screening",
        "aucs": "area under the curve",
        "auc": "area under the curve",
        "ai": "artificial intelligence",
        "a.i.": "artificial intelligence",
        "ai-fa": "artificial intelligence-inferred-fluorescein angiography",
        "aic": "akaike information criterion",
        "al": "axial length",
        "amd": "age-related macular degeneration",
        "armd": "age-related macular degeneration",
        "anns": "artificial neural networks",
        "ann": "artificial neural network",
        "anti-vegf": "anti-vascular endothelial growth factor",
        "ants-syn": "advanced normalization tools symmetric image normalization",
        "ants": "advanced normalization tools",
        "aqe": "automated quality evaluation",
        "ar": "augmented reality",
        "arf": "amblyopia risk factors",
        "aria": "automatic retinal image analysis",
        "asd": "autism spectrum disorder",
        "as-octa": "anterior segment optical coherence tomography angiography",
        "as-oct": "anterior segment optical coherence tomography",
        "asimov": "automated segmentation of mouse optical coherence tomography volumes",
        "automl": "automated machine learning",
        "avr": "arterio-venous ratio",

        "bbfl": "batch-balanced focal loss",
        "bcva": "best-corrected visual acuity",
        "bs": "berger's space",
        "bf": "bright-field",
        "bm": "bruch's membrane",
        "bpnn": "back-propagation neural network",

        "cadx": "computer aided-diagnosis",
        "cade": "computer-aided detection",
        "cad": "computer-aided diagnosis",
        "cams": "class activation maps",
        "catt": "comparison of age-related macular degeneration treatment trials",
        "ccc": "continuous curvilinear capsulorrhexis",
        "cdmd": "contour detection model based on degradation",
        "cfps": "color fundus photographs",
        "cfp": "color fundus photography",
        "cf": "color fundus",
        "cgan": "conditional generative adversarial network",
        "clahe": "contrast-limited adaptive histogram equalization",
        "clm": "classification localization map",
        "cme": "cystoid macular edema",
        "cmvr": "cytomegalovirus retinitis",
        "cnns": "convolutional neural networks",
        "cnn's": "convolutional neural networks",
        "cnn": "convolutional neural network",
        "cnv": "choroidal neovascularization",
        "conan": "consensus on neovascular amd nomenclature",
        "csc": "central serous chorioretinopathy",
        "csf": "cerebrospinal fluid",
        "cst": "central subfield thickness",
        "csvd": "cerebral small vessel disease",
        "ct": "computed tomography",
        "chatgpt": "chatgpt",
        "chatgpt plus": "chatgpt plus",
        "crora": "complete retinal pigment epithelium and outer retinal atrophy",
        "cvd": "choroidal vascular density",
        "cvi": "choroidal vascular index",

        "dcnns": "deep convolutional neural networks",
        "dcnn": "deep convolutional neural network",
        "dcp": "deep capillary plexus",
        "ded": "dry eye disease",
        "dhi": "diameter hole index",
        "dl": "deep learning",
        "dla": "deep learning algorithm",
        "dls": "deep learning system",
        "dm": "diabetes mellitus",
        "dnns": "deep neural networks",
        "dnn": "deep neural network",
        "dme": "diabetic macular edema",
        "dr": "diabetic retinopathy",
        "dri": "deep-range imaging",
        "dss": "decision support system",
        "dvp": "deep vascular plexus",
        "dvs": "dynamic vision sensor",

        "ecm": "extracellular matrix",
        "ehrs": "electronic health records",
        "ehr": "electronic health record",
        "elp": "effective lens position",
        "elm": "external limiting membrane",
        "efcm": "enhanced fuzzy c-means",
        "erg": "electroretinogram",
        "erms": "epiretinal membranes",
        "erm": "epiretinal membrane",
        "etdrs": "early treatment diabetic retinopathy study",
        "eu": "european union",
        "ez": "ellipsoid zone",

        "fa": "fluorescein angiography",
        "faf": "fundus autofluorescence",
        "faz": "foveal avascular zone",
        "fce": "focal choroidal excavation",
        "fcm": "fuzzy c-means",
        "fcn": "fully convolutional network",
        "fda": "food and drug administration",
        "fds": "family doctors",
        "fdt": "frequency doubling technology",
        "fd": "family doctor",
        "fe": "finite element",
        "ffa": "fundus fluorescein angiography",
        "fps": "fundus photographs",
        "fp": "fundus photograph",
        "fs": "fibrotic scar",
        "fvped": "fibrovascular pigment epithelium detachment",

        "gans": "generative adversarial networks",
        "gan": "generative adversarial network",
        "gcl": "ganglion cell layer",
        "glms": "generalized linear models",
        "glm": "generalized linear model",
        "gon": "glaucomatous optic neuropathy",
        "glaucoma": "glaucoma",
        "gps": "glaucoma probability scores",

        "hcq": "hydroxychloroquine",
        "hdl": "high-density lipoprotein",
        "hes": "hospital eye services",
        "hf": "heart failure",
        "hill-rbf": "hill-radial basis function",
        "hiv": "human immunodeficiency virus",
        "hr": "hypertensive retinopathy",
        "hrf": "hyperreflective retina foci",
        "hrm": "hyperreflective material",
        "hrt": "heidelberg retina tomography",

        "iai": "intravitreal aflibercept injection",
        "iamd": "intermediate age-related macular degeneration",
        "icl": "implantable collamer lens",
        "idf": "international diabetes federation",
        "idp": "iowa detection program",
        "idrid": "indian diabetic retinopathy image dataset",
        "ik": "infectious keratitis",
        "iioct": "instrument-integrated optical coherence tomography",
        "ilm": "internal limiting membrane",
        "inl": "inner nuclear layer",
        "iol": "intraocular lens",
        "iomt": "internet of medical things",
        "ipl": "inner plexiform layer",
        "ips": "image quality probability score",
        "ir": "infrared",
        "irds": "inherited retinal degenerations",
        "ird": "inherited retinal degeneration",
        "irf": "intraretinal fluid",
        "ivan": "inhibition of vegf in age-related choroidal neovascularisation",
        "ivcm": "in vivo confocal microscopy",
        "ivt": "intravitreal injection",

        "jm-oct": "jones matrix optical coherence tomography",
        "joi": "japan ocular imaging",
        "jos": "japanese ophthalmological society",

        "lc": "lamina cribrosa",
        "ld": "light damage",
        "libs": "laser-induced breakdown spectroscopy",
        "lim": "lens-induced myopia",
        "llct": "lesion-localization convolution transformer",
        "llms": "large language models",
        "llm": "large language model",
        "ltp": "long-term plasticity",
        "lvcl": "large-vessel choroidal layer",

        "mas": "microaneurysms",
        "ma": "microaneurysm",
        "mc": "multicolor",
        "ml": "machine learning",
        "mac": "macula",
        "mdss": "medical decision support system",
        "mcc": "matthew's correlation coefficient",
        "mlcs": "machine learning classifiers",
        "mlc": "machine learning classifier",
        "mlp": "multilayer perceptron",
        "mh": "macular holes",
        "mfergs": "multifocal electroretinograms",
        "mferg": "multifocal electroretinogram",
        "mgrf": "markov-gibbs random field",
        "mnv": "macular neovascularization",
        "m.h.": "macular holes",
        "mp": "microperimetry",
        "mri": "magnetic resonance imaging",
        "ms": "multiple sclerosis",
        "msg": "monosodium glutamate",
        "msi": "multispectral imaging",
        "mtann": "massive training of the artificial neural network",
        "mtro": "multi threshold-based remora optimization",
        "mvcl": "medium-vessel choroidal layer",

        "namd": "neovascular age-related macular degeneration",
        "nfs": "nonfibrotic scar",
        "nht": "neurological hemifield test",
        "nlp": "natural language processing methods",
        "nmlf": "nucleus of the medial longitudinal fasciculus",
        "nmosd": "neuromyelitis optica spectrum disorders",
        "nm": "non-mydriatic",
        "nns": "neural networks",
        "nn": "neural network",
        "non-dr": "non-diabetic retinopathy",
        "non-on": "non-optic neuritis",
        "np": "non-perfusion",
        "npdr": "non-proliferative diabetic retinopathy",
        "nrdr": "non-referable diabetic retinopathy",
        "nsr": "neurosensory retina",
        "nucs": "nuclear cataracts",
        "nuc": "nuclear cataract",
        "nv": "neovascularization",

        "ob/gyn": "obstetrics and gynecology",
        "od": "optic disc",
        "oct": "optical coherence tomography",
        "octa": "optical coherence tomography angiography",
        "oct-a": "optical coherence tomography angiography",
        "okap": "ophthalmic knowledge assessment program",
        "odd": "optic disc drusen",
        "ohts": "ocular hypertension treatment study",
        "oir": "oxygen-induced retinopathy",
        "opd": "outpatient department",
        "on": "Optic neuritis",
        "onhd": "optic nerve head drusen",
        "onh": "optic nerve head",
        "onl": "outer nuclear layer",
        "opl": "outer plexiform layer",
        "ort": "outer retinal tubulation",

        "pbl": "problem-based-learning",
        "pca": "principal component analysis",
        "pcbm": "polythiophene derivative/fullerene derivative",
        "pclt": "pearson's correlation-based local topography",
        "pd": "parkinson's disease",
        "pdgf": "platelet-derived growth factor",
        "pdr": "proliferative diabetic retinopathy",
        "pdt": "photodynamic therapy",
        "ped": "pigment epithelial detachment",
        "phc": "personalized healthcare",
        "plr": "pupil light reflex",
        "pm": "pathologic myopia",
        "ppf": "paired-pulse facilitation",
        "ppg": "photoplethysmography",
        "poag": "primary open-angle glaucoma",
        "prd": "photoreceptor degeneration",
        "ps-gan": "perceptual structure generative adversarial network",
        "ps-oct": "polarization-sensitive optical coherence tomography",
        "pvd": "posterior vitreous detachment",
        "pwv": "pulse wave velocity",
        "pxe": "pseudoxanthoma elasticum",

        "rbs": "radial basis function",
        "rct": "randomized controlled trial",
        "rd": "retinal detachment",
        "rdr": "referable diabetic retinopathy",
        "red": "retinal exudates and/or drusen",
        "rgcs": "retinal ganglion cells",
        "rgc": "retinal ganglion cell",
        "rnfl": "nerve fiber layer",
        "rpe": "retinal pigment epithelium",
        "roc": "receiver operating characteristic",
        "rois": "regions of interest",
        "roi": "region of interest",
        "rop": "retinopathy of prematurity",
        "ros": "retinal organoids",
        "rp": "retinitis pigmentosa",
        "rpd": "reticular pseudodrusen",
        "rrt": "red reflex test",
        "rv": "retinal vascular",
        "rvo": "retina vein occlusion",
        "rvsv": "retinal vascular shadow view",

        "sans": "spaceflight associated neuro-ocular syndrome",
        "sap": "standard automated perimetry",
        "sas": "segmentation accuracy score",
        "scdd": "scotopic contour deformation detection",
        "scp": "superficial capillary plexus",
        "scr": "sickle cell retinopathy",
        "scz": "schizophrenia",
        "sd-oct": "spectral-domain optical coherence tomography",
        "sdoct": "spectral-domain optical coherence tomography",
        "sec": "smart eye camera",
        "ser": "spherical equivalent refraction",
        "she": "subretinal hyperreflective exudation",
        "shrm": "subretinal hyperreflective material",
        "si": "subretinal injection",
        "sia": "surgically induced astigmatism",
        "slos": "scanning laser ophthalmoscopes",
        "slo": "scanning laser ophthalmoscope",
        "soks": "second-order kernels",
        "sok": "second-order kernel",
        "sped": "serous pigment epithelial detachment",
        "sps": "sufficient image quality probability score",
        "srf": "subretinal fluid",
        "srt": "selective retina laser treatment",
        "ss-oct": "swept-source optical coherence tomography",
        "stgd": "stargardt disease",
        "stp": "short-term plasticity",
        "svcl": "small-vessel choroidal layer",
        "svm": "support vector machine",
        "svp": "superficial vascular plexus",

        "tao": "thyroid-associated ophthalmopathy",
        "td-oct": "time-domain optical coherence tomography",
        "tia": "target induced astigmatism",
        "tmv": "total macular volume",
        "trfs": "traditional risk factors",
        "trf": "traditional risk factor",
        "tta": "test time augmentation",

        "uav": "unmanned aerial vehicle",
        "u.s.": "united states",
        "uwfa": "ultra-widefield angiography",
        "uwf": "ultra-widefield",
        "ufis": "ultra-widefield fundus images",
        "ufi": "ultra-widefield fundus image",

        "vas": "visual acuities",
        "va": "visual acuity",
        "vegf": "vascular endothelial growth factor",
        "vf": "visual field",
        "vfi": "visual field index",
        "vgg-19": "virtual geometry group-19",
        "vlps": "visual light perceptions",
        "vlp": "visual light perception",
        "vo": "vaso-obliteration",
        "vr": "virtual reality",
        "vss": "vascular severity score",
        "vtdr": "vision threatening diabetic retinopathy",
        "vv": "vascular volume",

        "wes": "word embeddings",
        "wga": "wild geese algorithm",
    }

    return replacements
