def definitions() -> dict[str, str]:
    field_dict: dict[str, str] = {
        "Abstract":	"AB",
        "Copyright Information": "CI",
        "Affiliation": "AD",
        "Investigator Affiliation": "IRAD",
        "Article Identifier": "AID",
        "Author": "AU",
        "Author Identifier": "AUID",
        "Full Author": "FAU",
        "Book Title": "BTI",
        "Collection Title": "CTI",
        "Conflict of Interest Statement": "COIS",
        "Corporate Author": "CN",
        "Create Date": "CRDT",
        "Date Completed": "DCOM",
        "Date Created": "DA",
        "Date Last Revised": "LR",
        "Date of Electronic Publication": "DEP",
        "Date of Publication": "DP",
        "Edition": "EN",
        "Editor": "ED",
        "Full Editor Name": "FED",
        "Entrez Date": "EDAT",
        "Gene Symbol": "GS",
        "General Note": "GN",
        "Grant Number": "GR",
        "Investigator Name": "IR",
        "Full Investigator Name": "FIR",
        "ISBN": "ISBN",
        "ISSN": "IS",
        "Issue": "IP",
        "Journal Title Abbreviation": "TA",
        "Journal Title": "JT",
        "Language": "LA",
        "Location Identifier": "LID",
        "Manuscript Identifier": "MID",
        "MeSH Date": "MHDA",
        "MeSH Terms": "MH",
        "NLM Unique ID": "JID",
        "Number of References": "RF",
        "Other Abstract": "OAB",
        "Other Copyright Information": "OCI",
        "Other ID": "OID",
        "Other Term": "OT",
        "Other Term Owner": "OTO",
        "Owner": "OWN",
        "Pagination": "PG",
        "Personal Name as Subject": "PS",
        "Full Personal Name as Subject": "FPS",
        "Place of Publication": "PL",
        "Publication History Status": "PHST",
        "Publication Status": "PST",
        "Publication Type": "PT",
        "Publishing Model": "PUBM",
        "PubMed Central Identifier": "PMC",
        "PubMed Central Release": "PMCR",
        "PubMed Unique Identifier": "PMID",
        "Registry Number/EC Number": "RN",
        "Substance Name": "NM",
        "Secondary Source ID": "SI",
        "Source": "SO",
        "Space Flight Mission": "SFM",
        "Status": "STAT",
        "Subset": "SB",
        "Title": "TI",
        "Transliterated Title": "TT",
        "Volume": "VI",
        "Volume Title": "VTI"
    }

    return field_dict
